Models/ErrorViewModel.cs
namespace pc1.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/OperarBolsa.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace pc1.Models
{
    public class OperarBolsa
    {
        public string? NombreApellido { get; set; }
        public string? CorreoElectronico { get; set; }
        public string? Fecha { get; set; }
        public string? Instrumento { get; set; }
        public decimal IGV { get; set; }
        public decimal Monto { get; set; }

        public decimal Comision { get; set; }

        public void CalcularOperacion()
        {
            IGV = Monto * 0.18m;
            Comision = Monto <= 300 ? 1 : 3;
        }
    }


}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using pc1.Models;

namespace pc1.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/OperarBolsaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using pc1.Models;

namespace pc1.Controllers
{
    public class OperarBolsaController : Controller
    {
        private readonly ILogger<OperarBolsaController> _logger;

        public OperarBolsaController(ILogger<OperarBolsaController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            ViewData["listaOperaciones"] = new List<OperarBolsa>();
            return View();
        }

        [HttpPost]
        public IActionResult Invertir(OperarBolsa operarbolsa)
        {
            List<OperarBolsa> listaOperaciones = new List<OperarBolsa>();
            operarbolsa.CalcularOperacion();
            listaOperaciones.Add(operarbolsa);
            ViewData["listaOperaciones"] = listaOperaciones;
            return View("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/OperarBolsa/index.cshtml
@model pc1.Models.OperarBolsa

@{
    ViewData["Title"] = "Operar Bolsa";
    var listaOperaciones = ViewData["listaOperaciones"] as List<OperarBolsa>;
}

<h1>Operar Bolsa</h1>

<form asp-controller="OperarBolsa" asp-action="Invertir" method="post">
    <div class="form-group">
        <label asp-for="NombreApellido">Nombre:</label>
        <input asp-for="NombreApellido" class="form-control" required>
    </div>
    <div class="form-group">
        <label asp-for="CorreoElectronico">Email:</label>
        <input asp-for="CorreoElectronico" class="form-control" required>
    </div>
    <div class="form-group">
        <label asp-for="Fecha">Fecha de Operación:</label>
        <input asp-for="Fecha" type=date class="form-control" required>
    </div>
    <div class="form-group">
        <label for="instrumento">Instrumento:</label><br>
        <input type="checkbox" id="sp" name="instrumento" value="S&P"> S&P<br>
        <input type="checkbox" id="dowJones" name="instrumento" value="Down Jones"> Down Jones<br>
        <input type="checkbox" id="bonosUS" name="instrumento" value="Bonos US"> Bonos US<br>
    </div>
    <div class="form-group">
        <label asp-for="Monto">Monto a Abonar:</label>
        <input asp-for="Monto" class="form-control" required>
    </div>
    <button type="submit" class="btn btn-primary">Invertir</button>

</form>

<table class="table">
    <thead>
        <tr>
            <th>Instrumento</th>
            <th>Fecha</th>
            <th>IGV</th>
            <th>Comisión</th>
        </tr>

    </thead>
    <tbody>
        @foreach (var operacion in listaOperaciones)
        {
            <tr>
                <td>@operacion.Instrumento</td>
                <td>@operacion.Fecha</td>
                <td>@operacion.IGV</td>
                <td>@operacion.Comision</td>
            </tr>
        }
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - pc1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/pc1.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">pc1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OperarBolsa"
                                asp-action="Index">Operar en Bolsa</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - pc1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>